backend:
 name: github
 repo: hupallor-prog/tabernaelsardi
 branch: main
media_folder: "public/images"
public_folder: "/images"
collections:
 - name: "restaurante"
   label: "Restaurante"
   files:
     - file: "src/content/data.json"
       label: "Datos"
       name: "data"
       fields:
         - { label: "Nombre", name: "name", widget: "string" }
         - { label: "Teléfono", name: "phone", widget: "string" }
         - { label: "Dirección", name: "address", widget: "string" }
